### ISSUE TITLE
can not find the function 'Matern32'

### ISSUE THREAD

**Issue by ljt1987** [TimothyRogers/vibration-NL-input-state#1]
Dear Timothy,

    Thank you for sharing your great work. When I tried your program, it seems that the function 'Matern32' is missing. Can you kindly provide it. Thanks.

**Comment by TimothyRogers** [comment]
This class is used to generate example data as a draw from a GP with a Matern 3/2 kernel. Required functions added in https://github.com/TimothyRogers/vibration-NL-input-state/commit/ebb72ad5467b95c747a9ec56f5f6496e37578dd6
